[package]
name = "bluzelle-example"
version = "0.1.0"
authors = ["vb <vbstreetz@gmail.com>"]
edition = "2018"

[dependencies]
bluzelle = { path = "../bluzelle" }
dotenv = "*"
tokio = { version = "0.2", features = ["full"] }